---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 51-worker-kargs
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
  # https://www.freedesktop.org/software/systemd/man/kernel-command-line.html
  kernelArguments:
    - psi=1
