= Storage

OpenShift uses the Kubernetes persistent volume (PV) framework to allow cluster
administrators to provision persistent storage for a cluster. Developers can use
persistent volume claims (PVCs) to request PV resources without having specific
knowledge of the underlying storage infrastructure.

== NFS

When using `+NFS+` as storage backend, the `+PV+` must be previously created.

[source,yaml]
----
include::nfs/etcd-backup-pv.yml[]
----

Create the object using the `+oc apply+` command on this file.

[source,shell]
----
oc apply -f nfs/etcd-backup-pv.yml
----

== Local Storage Operator (LSO)

Install `+Local Storage Operator+` from Openshift marketplace.

[source,shell]
----
oc apply -f lso/
oc get installplan -n openshift-lso \
    -o go-template='
        {{range .items}}
            {{if eq .spec.approved false}}
                {{.metadata.name}}{{"\n"}}
            {{end}}
        {{end}}' |\
            xargs oc patch installplan -n openshift-lso \
                --type=merge -p='{"spec": {"approved": true}}'
----

Add a disk to each node and label these nodes to schedule the persistent volumes
created by the `+LSO+` on them.

[source,shell]
----
oc label node worker00 local.storage.openshift.io/lso=prometheus-scsi-fs
oc label node worker01 local.storage.openshift.io/lso=prometheus-scsi-fs
oc label node worker02 local.storage.openshift.io/lso=generic-scsi-fs
----

Get the device ID for the new disk in each node.

[source,shell]
----
$ ls -al /dev/disk/by-id/
lrwxrwxrwx. 1 root root scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-1 -> ../../sdb
----

Update the `+LocalVolume+` object definition with the disk ID in each node.

[source,yaml]
----
include::lso/local-volumes/generic-scsi-fs.yml[]
----

Create the object using the `+oc apply+` command on this file.

[source,shell]
----
oc apply -f lso/local-volumes
----

== References

- https://github.com/openshift/local-storage-operator
- https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage
