---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ephemeral
spec:
  kafka:
    replicas: 1
    version: 2.7.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources:
      requests:
        memory: 2Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "1"
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
      - name: ingress
        port: 9094
        type: route
        tls: true
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: 2.7
      inter.broker.protocol.version: 2.7
      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
    storage:
      type: ephemeral
    # authorization:
    #   type: simple
  zookeeper:
    replicas: 1
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 30
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        requests:
          memory: 128Mi
          cpu: 200m
        limits:
          memory: 256Mi
          cpu: 500m
    userOperator:
      reconciliationIntervalSeconds: 30
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          memory: 128Mi
          cpu: 200m
        limits:
          memory: 256Mi
          cpu: 500m
    tlsSidecar:
      resources:
        requests:
          memory: 64Mi
          cpu: 200m
        limits:
          memory: 128Mi
          cpu: 500m
