---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: openshift-operators
spec:
  name: quay-operator
  channel: "quay-v3.5"
  installPlanApproval: Automatic
  source: redhat-operators-disconnected
  sourceNamespace: openshift-marketplace
