---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh-operator
  labels:
    operators.coreos.com/servicemeshoperator.openshift-operators: ""
spec:
  name: servicemeshoperator
  channel: "stable"
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
