apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-marketplace-disconnected
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Marketplace (Disconnected)
  image: registry.ocp.bmlab.int:5443/openshift4/olm-redhat-marketplace-index:v4.7-v1
  sourceType: grpc
  publisher: Disconnected
updateStrategy:
  registryPoll: 
    interval: 8h
