global:
  resolve_timeout: 5m
receivers:
  - name: default
  - name: watchdog
  - name: webhook
    webhook_configs:
      - url: "http://alertmanager-receiver.openshift-monitoring.svc:6725"
        send_resolved: true
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30s
  receiver: default
  routes:
    - receiver: watchdog
      match:
        alertname: Watchdog
      continue: yes
    - receiver: webhook
      continue: yes
