---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer
  labels:
    app: resource-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-consumer
  template:
    metadata:
      labels:
        app: resource-consumer
    spec:
      containers:
        - name: resource-consumer
          image: gcr.io/k8s-staging-e2e-test-images/resource-consumer:1.9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: 128Mi
            limits:
              cpu: "500m"
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: resource-consumer
  labels:
    app: resource-consumer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: resource-consumer
  sessionAffinity: None

---
apiVersion: v1
kind: Route
metadata:
  name: resource-consumer
  labels:
    app: resource-consumer
spec:
  to:
    kind: Service
    name: resource-consumer
    weight: 100
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
